// <auto-generated />
namespace Entityframework.HAI._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201611170242235_Product DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
